# Use Python base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory in the container
WORKDIR /usr/src/app

# Copy and install dependencies
COPY ./user_service/requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY ./user_service /usr/src/app

# Expose the port where the Flask app runs
EXPOSE 5000

# Define the command to start the Flask application
CMD ["python", "run.py"]
